Re-introduce snapshots.debian.org by using local keyring

diff --git a/Singularity-rstudio b/Singularity-rstudio
--- a/Singularity-rstudio
+++ b/Singularity-rstudio
@@ -114,6 +114,19 @@ From: r-py.sif
 
 
 %setup
+
+  if [ -z "${DEBUG-}" ]; then
+    # make sure it doesn't fail
+    git status -s &>/dev/null
+    if [ ! "$(git status -s | wc -l)" = "0" ]; then
+      echo "Working dir dirty!" >&2
+      exit 1
+    fi 
+    git rev-parse HEAD >"$SINGULARITY_ROOTFS/commit"
+  else
+    echo "debug" > "$SINGULARITY_ROOTFS/commit"
+  fi
+
   install -Dv \
     scripts/rstudio_auth.sh \
     ${SINGULARITY_ROOTFS}/usr/lib/rstudio-server/bin/rstudio_auth
@@ -174,8 +187,11 @@ From: r-py.sif
   session-timeout-minutes=0
 EOF
   
-  echo "create_date $(date -u +'%Y-%m-%dT%H:%M:%SZ')"  >> "SINGULARITY_LABELS"
+#  echo "create_date $(date -u +'%Y-%m-%dT%H:%M:%SZ')"  >> "SINGULARITY_LABELS"
 
+  # Write the current git commit as label
+  echo "git_commit $(cat /commit)" >> "$SINGULARITY_LABELS"
+  rm /commit
 
   # Clean up
   umount /var/lib/apt
